name: Publish to NPM

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      # Добавляем проверку наличия файлов
      - name: Check files
        run: |
          ls -la
          echo "Checking for index.js..."
          if [ ! -f index.js ]; then
            echo "index.js is missing!"
            exit 1
          fi

      - name: Authenticate with npm
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_PUBLISH_TOKEN }}" > ~/.npmrc

      - name: Install dependencies
        run: npm install

      # Добавляем шаг для проверки содержимого пакета
      - name: Pack and check contents
        run: |
          npm pack
          tar -tvf *.tgz

      - name: Publish to npm
        run: npm publish --access public
